version: "3.0"
services:
  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/nginx.conf
  admin:
    image: "devnightowl094/dockertest:latest"
    ports:
      - "3000:3000"
  api:
    image: "devnightowl094/dockertest2:latest"
    ports:
      - "3001:3001"
  landing:
    image: "devnightowl094/dockertest3:latest"
    ports:
      - "3002:3002"
