# 노드 LTS 경량 버전을 베이스로 시작
FROM node:lts-alpine

# 워킹 디렉토리 세팅
WORKDIR /app

# 호스트 파일을 복사해서 컨테이너에 위치
COPY . /app

# 이미지 파일 시스템에서 커맨드 실행
RUN npm install

# PORT 개방
EXPOSE 3002

# 컨테이너에서 커맨드 실행
CMD [ "npm", "start" ]